### PR TITLE
Selective localization and constrained centres from Marianetti et al.  [PRB 90, 165125 (2014)]

### PR DESCRIPTION
**Pull request by VVitale**
Here is an implementation of the Marianetti et al. work [PRB 90, 165125 (2014)] for selectively localize a subset of functions, also known as Objective Wannier Functions and also for constraining their centres.  
A new example, i.e. Example26 on Gallium Arsenide has been added to the list, which reproduce some of the result in the above mentioned paper. Moreover, the Tutorial and user_guide tex files have been modified accordingly.  There, it is explained how the algorithm works and how to use the new keywords. A substantial part of the current implementation, particularly the section on selective localization, is based on prior work done by Charles T. Johnson during his MSci project.

### CODE REVIEW

**Comment by VVitale** [comment]
I noticed that I removed all the trailing spaces in the doc/user_guide/parameters.tex and I moved some of the definitions for the SCDM around. The information contained in the file however is exactly the same as before

**Comment by VVitale** [comment]
I'll create a test for this feature, in order to improve the codecov result

**Comment by VVitale** [comment]
I have fixed the conflicts between this repo and develop due to recent additions in PR #193 and PR #194

**Comment by mostofi** [comment]
I've opened a pull request to your branch with some updates to the tutorial and user guide. 

Additionally:

(1) May I suggest that you rename the SLWF variables? 

sel_loc_num --> slwf_num
sel_loc_constrain --> slwf_constrain
sel_loc_constrain_lambda --> slwf_lambda
centre_constraints --> slwf_centres

This will need a search and replace through the code and the tutorial and user guide.

(2) There is no need to write the value of lambda to the output file at each Wannierisation iteration, since its value is fixed. May I suggest that this behaviour is changed both in the code and, correspondingly, in the user guide?

Thanks.

**Comment by mostofi** [comment]
PS There are a couple of minor conflict with parameters.F90 in the develop branch. Please could you fix before updated the PR? Thanks.

**Comment by VVitale** [comment]
I have fixed the minor conflicts with parameters.F90. 
Merged @mostofi pull request with changes for tutorial and user_guide.
I have changed the key words as suggested by @mostofi in the parameters.F90 and wannierise.F90 as well as in the tutorial.tex and parameters.tex. 
I have modified the gaas.win and related benchmark files in test-suite/tests/testw90_example26
Finally, I have modified the GaAs.win file in examples/example26

**Comment by mostofi** [comment]
@VVitale, I've sent you a pull request, fixing a few typos for the SLWF parts in the user guide.

I also noticed that lambda is still printed every wannierisation iteration (as discussed, it need only be reported at the start of the calculation). Please could you fix this, as well as two instances in userguide/files.tex where it is present?

**Comment by VVitale** [comment]
@mostofi, done

**Pull request merged**
