### PR TITLE
Adding ws_search_size also in postw90

### LINKED ISSUE #331: ERROR in wigner_seitz: error in finding Wigner-Seitz points
Hi Wannier90 developers, 

I have the above error. At first, I encountered "error in finding Wigner-Seitz points" in the hamiltonian_wigner_seitz subroutine when running wannier90.x. I increased ws_search_size from 2 to 4 and it works.

When I tried to run postw90.x, I get the above error. For some reason, the error message and the vectors are not fully printed out when I tried running postw90.x again.

I have attached the *.win, *.wout, *.wpout and a data file which contains tot and mp_grid from the wigner_seitz subroutine. 

[TaAs.win.txt](https://github.com/wannier-developers/wannier90/files/4671297/TaAs.win.txt)
[TaAs.wout.txt](https://github.com/wannier-developers/wannier90/files/4671281/TaAs.wout.txt)
[TaAs.wpout.txt](https://github.com/wannier-developers/wannier90/files/4671283/TaAs.wpout.txt)
[ws.txt](https://github.com/wannier-developers/wannier90/files/4671284/ws.txt)

Can someone kindly tell me why I have this error?

Thanks. 

Regards,
Truman

### PR DESCRIPTION
**Pull request by gibertini**
This fixes #331, adding the use of ws_search_size also in postw90.

### CODE REVIEW

**Comment by trumanmiguel** [comment]
Hi @gibertini. I just saw this pull request. I assume that the code has been fixed?

**Comment by gibertini** [comment]
@trumanmiguel : yes, the code should be fixed now. Let's wait for the pull request to be accepted.

**Review by giovannipizzi — APPROVED** [review]
Thanks Marco @gibertini !

**Comment by giovannipizzi** [comment]
@trumanmiguel this is now merged in the main code. Could you please check if this works as expected or still has issues? Thanks!

**Comment by trumanmiguel** [comment]
Hi @giovannipizzi. The code works fine when I used it in my calculation. Thanks.

**Comment by PeterKraus** [comment]
@giovannipizzi @gibertini:

I think @djitech13 and I just ran into the same issue. Current blame in the `develop` branch shows that the changes might have been reverted. Maybe I'm wrong though!

https://github.com/wannier-developers/wannier90/blame/develop/src/postw90/postw90_common.F90#L1952-L1957

**Pull request merged**
