### PR TITLE
separate routine for reading the overlaps matrix

### PR DESCRIPTION
**Pull request by jimustafa**
This PR is exploring the possibility of separate routines for reading the input matrices (eigenvalues, overlaps, projections, and so on). A standalone library of this sort could make a Python wrapper relatively straightforward.

### CODE REVIEW

**Comment by stepan-tsirkin** [comment]
Hi @jimustafa ,
this PR looks like a step towards a good direction, although I am not a maintainer of wanier90.

Just note, that much of the reading in input matrices is implemented in python in the following [file](https://github.com/wannier-berri/wannier-berri/blob/master/wannierberri/__w90_files.py) of Wannier-Berri package. Please, look if you find it useful.

**Comment by jimustafa** [comment]
Greetings @stepan-tsirkin. Yes, I am a bit familiar with your package, looks like it provides a lot of great functionality. Was thinking a separate library for I/O within wannier90, and a python interface with f2py, could be a nice addition. May help to consolidate the variety of python implementations out there.

**Comment by stepan-tsirkin** [comment]
@jimustafa , sure, it will be useful. If such l/O library  becomes a native part of wannier90, I will consider using it instead of pythonic parsing of the files.

**Comment by jimustafa** [comment]
It would seem that this functionality may already be part of or planned for the library developments. Hey @mostofi, does Jerome have a public GitHub profile so that I may @-mention him in any future discussions?

**Comment by mostofi** [comment]
Yes, it's @JeromeCCP9

**Pull request closed without merging**
