### PR TITLE
Previous changes to plot.f90 from Arash 

### PR DESCRIPTION
**Pull request by VVitale**
Changes made to generate cube files for non orthogonal unit cells

### CODE REVIEW

**Comment by jryates** [comment]
Valerio, Thanks for this. Could you also document the new keyword in the user guide please.
Jonathan

**Comment by VVitale** [comment]
Hi Jonathan, sorry for the late reply. There is no new keyword to add, but I should probably change the sentence in the user guide where it says that only orthogonal lattice vectors are allowed when using a Gaussian cube format.

**Comment by jryates** [comment]
It looks like there is a new input variable called wannier_plot_scale

**Comment by VVitale** [comment]
Oops, sorry you are absolutely right!

**Pull request merged**
