### PR TITLE
Cmake

### PR DESCRIPTION
**Pull request by LecrisUT**
I have rebased the branch in #440 to point to the current `develop` head. Also reconfigured the GitHub workflows to run through ctest. Many things were deleted from the old workflow as I copied the workflow from other projects. If there is something missing that should be there, let me know.

Also there are a few improvements from the last cmake PR:
- More readable top-level CMakeLists
- Fixed the install path of the Fortran modules to point to ABI specific location. See comments inside for more details

### CODE REVIEW

**Comment by LecrisUT** [comment]
@JeromeCCP9 I have rebased your commits to the current `develop` HEAD so that hopefully this can be merged ahead of the other. Would appreciate if you could assign someone to look at the test failures

**Comment by LecrisUT** [comment]
Note: `wannier_lib.F90` is not properly installed for this one because the subroutines are global. `libdev-interface` should fix that and I have fixed them in https://github.com/LecrisUT/wannier90/tree/cmake

**Comment by JeromeCCP9** [comment]
@LecrisUT This is great!  wannier_lib.F90 is obsolete now and I'll remove it, and I'll fix the test failures.  I'll go through this now and reply again...

**Review by JeromeCCP9 — APPROVED** [review]

**Comment by LecrisUT** [comment]
> wannier_lib.F90 is obsolete now

Indeed, but I think for this PR, we just make the basic cmake builder and CI so that there is a base framework to work with. It would not be production ready, but then when `libdev-interface` we include the relevant parts.

There are a few other minor issues that should be addressed, but let's focus on this PR to get the github action running, then I can address some of them. E.g. besides this PR, I think we also need #444 to properly test the packaging, such as the usage of `find_package(Wannier90)`. Can you ping someone with write privileges to look at that one?

**Comment by LecrisUT** [comment]
@JeromeCCP9 I want to squash and redo this PR keeping the makefile build for now. Are you ok with losing your commit authorship for this?

**Comment by JeromeCCP9** [comment]
Hi!  I guess you discussed with Giovanni P at the ESL meeting?

When we talked last week, along with some other folks, we decided indeed to keep the usual makefile and setup cmake in parallel (despite this being a bit messy).

What would you like to do?  My plan was to close this PR and setup a new one adding (a slimmed down) CMakeLists setup to that.

**Comment by LecrisUT** [comment]
Yes, basically I want to:
- PR1: Add the CMake build (more or less this version)
- PR1: Expand (and reorganize) the github actions to cover more compilers and build variants. For now I will put it in the same PR in order to run tests properly, but later we can separate them if needing more discussions.
- PR2: Test and fix macos build. @giovannipizzi I will discuss more in that PR so we can have some CI tests to share the error logs

**Comment by JeromeCCP9** [comment]
That sounds great to me!

In which case I will not touch the cmake etc for a while unless you mention me here or so (you can also email me if I am slow etc).

**Comment by LecrisUT** [comment]
Expect PRs in a few min ;)

**Comment by LecrisUT** [comment]
Superseeded by #487

**Pull request closed without merging**
