### PR TITLE
Modern cmake

### PR DESCRIPTION
**Pull request by LecrisUT**
Here is a more modern approach to cmake design

Please rebase non-cmake commits out  of the cmake branch.

@sstgfbc, Jerome Jackson, please review

### CODE REVIEW

**Comment by JeromeCCP9** [comment]
Dear Cristian,

this is very interesting!  This branch was only meant to demonstrate that the use of cmake would not be too difficult; I only spent an afternoon/evening on it (and I don't really like cmake) so it was just sketchy.  I pushed it in order to gather some feedback.  Actually this is the first feedback!

At the moment we're mostly working on another branch, which this one is a small deviation from, but yes certainly we can make this a discrete change.

I will look at your work and I certainly believe that this is a big improvement over what I threw together.

It is quite likely that nothing much will happen before the Wannier Developer meeting in May.  (Were you aware of the meeting?)  -- perhaps you and I can telephone/zoom during this meeting (15-19 May) and discuss?  Or you could give a short presentation to the group?

Thank you very much for this,
yours, Jerome / Barry

**Comment by LecrisUT** [comment]
Sorry I was caught up and didn't manage to write the reply. Note that I've added a [silly change](https://github.com/wannier-developers/wannier90/pull/441/files#diff-e90ef91cbc0b47e752209423142389f62c65d4ee85b3a49bef6ed49d41f8dd70R410) to get it to build initially.

I think we can have a quick chat on those days or before if you think it is helpful. Is there something speficif that you would like to discuss there, like what are the benefits, changes needed etc?

**Comment by LecrisUT** [comment]
I will add some minimum todo to finish the cmake implementation:
- Change the tests to native cmake or more accessible python script
- Change the CI to use ctest

Good-to-have that can be implemented:
- doxygen documentation building. Works very well with sphinx and read-the-docs workflow
- proper unit-testing using plain fortran functions

**Comment by JeromeCCP9** [comment]
Yes, that's great!  We are really grateful that you have taken the time to do this work.

Yes, let's discuss by zoom during the meeting, if you have some time?   If anyone has strong opinions, I will ask them to join us.  Personally I think it is really a good thing for the project to adopt cmake now (even if I don't like it so much!) and it would be good if we adopt this change at the meeting.

I'm not sure where you are geographically: the meeting is near Manchester, UK; are there some times in the UK daytime that would work for you?

The reason why I added the cmake on top of our developments is because we changed quite a few things, including dependencies, and it would have needed some extra work to make the old code work.  Probably that's not worth the effort because we want to merge our main changes also at the meeting.

Totally agree about the need to improve/replace the testing system.  The python is quite old and maybe not maintained anymore.

J.

**Comment by LecrisUT** [comment]
I am on German time-zone currently so any time is suitable. You can email me the details either on the email in my commits or the one in my github profile.

**Comment by JeromeCCP9** [comment]
Ok, great.  We will be in touch in May.  Thank you for this!  J.

**Comment by JeromeCCP9** [comment]
Dear Cristian,

are you available to talk to us about Wannier90 on Thursday afternoon, say at 15:00 or 15:00 EST (2 pm or 2:30 UK time)?  You could join us on this zoom link: https://ukri.zoom.us/j/92679165297

The meeting is very informal and probably only some of us are concerned with the the build system, but it would be great if you would like to join us, even if just for 15 min (say).

Let me know if this would work for you.  Thank you again for your work.

Yours, Jerome

________________________________________

**Comment by LecrisUT** [comment]
Tomorrow will work with me.

Be aware that you have sent this via github such that zoom link is publicly visible. If possible please generate a new zoom link and sent it privately to me at my email in the github profile or the one in my commits (not stating it directly in the message to avoid bots that scrape emails).

PS: I wanted to send you the email directly but I couldn't find any on your profile.

**Pull request merged**
