### PR TITLE
add more whitespace checking and fixes

### PR DESCRIPTION
**Pull request by jimustafa**

### CODE REVIEW

**Comment by jimustafa** [comment]
Forgot about https://github.com/pseewald/fprettify/issues/96... Will update this PR after #402 is merged.

**Comment by jimustafa** [comment]
Wanted to check on this... OK to merge?

**Review by JeromeCCP9 — APPROVED** [review]
Approving apparently cosmetic changes.

**Comment by JeromeCCP9** [comment]
Some files not in the PR have whitespace errors.  I'll close this merge request and start a new one which runs through.
J.

**Pull request merged**
