### PR TITLE
Ws distance tol

### PR DESCRIPTION
**Pull request by greschd**
This PR adresses issue #101 . The changes are as follows:

* The check in ws_distance.F90 (line 156) is made more lenient, to avoid false errors
* The check for positions of equivalent distance (line 236) has two changes:
  * The absolute difference in distance is calculated instead of the relative one
  * The tolerance can now be changed by the user (``ws_distance_tol`` parameter)

The reason I'm marking this as work in progress is that the change in the second check breaks the test ``si_geninterp_wsdistance``. I have investigated this, and it seems to be because the Wannier positions are very close, but not exactly equal, in the tested example. Due to the change from relative to absolute distance there's no value for ``ws_distance_tol`` which exactly keeps the previous behavior. @paulatz , what is your take on this? Can we safely replace the test data?

### CODE REVIEW

**Comment by paulatz** [comment]
Hello, I got a bit distracted away from this issue. I think what Dominik proposes is correct, the consistency check should not be necessary and can cause problems. I think we can replace the test data with no problem. However, on my computer using the Dominik version (but maybe I'm not cloning the correct git branch) or the upstream one gives the same result for the test. I guess we may be close to the tolerance, maybe it would be better to increase the convergence threshold of the minimization, to avoid having to avoid having spurious test errors?

**Comment by paulatz** [comment]
Ok, I managed to find the new version of the code an I tested it extensively. It is indeed impossible to reproduce the same results of the test because of the change of the threshold from relative to absolute, bit it does not make a real difference. 

The results are actually almost identical when using ws_distance_tol=5.d-5. It does not really make any difference if two WF which are almost on the boundary of each other's WS cell are put inside or outside, or on the border.

Personally, I approve this new version from Dominik and updating of the test.

**Comment by greschd** [comment]
Thanks for testing Lorenzo. I updated the PR with the new test results.

**Comment by greschd** [comment]
Alright, I added the section describing the input parameter. For the unit: the cartesian coordinates are always in Angstrom internally, correct?
Yes, this closes #101.

As a side note, the "plot parameters" table is now too long to fit on its page. I'm guessing we'll fix that before the next release (since there might be more parameters coming), right?

**Pull request merged**
